name: Secret Demo

on: workflow_dispatch

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Show Configured Secret (Masked)
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -z "$MY_API_KEY" ]; then
            echo "API_KEY n√£o encontrada ou vazia."
          else
            echo "API_KEY configurado"
          fi
